defaults:
- dataset: default
- model: phi3
- training: default
- _self_

working_dir: /scratch/Alberghi/new_results # ${hydra:runtime.cwd}
results_dir: ${working_dir}/results
experiment_name: "n5_tokens_ibac"

hydra:
  job:
    name: ${experiment_name}
  run:
    dir: ${results_dir}/${experiment_name}
