defaults:
- dataset: default
- model: phi3
- training: default
- _self_

working_dir: /data/dynamic_programming # ${hydra:runtime.cwd}
results_dir: ${working_dir}/results
experiment_name: "p5_cot_1"

hydra:
  job:
    name: ${experiment_name}
  run:
    dir: ${results_dir}/${experiment_name}
