defaults:
- dataset: default
- model: phi3
- training: default
- _self_

working_dir: /scratch/Alberghi/ # ${hydra:runtime.cwd}
results_dir: ${working_dir}/results_final_final_final
experiment_name: "p5_2"

hydra:
  job:
    name: ${experiment_name}
  run:
    dir: ${results_dir}/${experiment_name}
